"""
Cloud Telemetry Simulator & Log Parser (Module 1)
==================================================
This module simulates real-world Cloud Infrastructure events (AWS CloudTrail,
Syslog Honeypot entries, and Network traffic logs). It demonstrates basic Python
log manipulation, data structures, and initial risk categorization.

Author: Senior Cloud Security Architect
Project: AI-Driven Autonomous Cloud Threat Intelligence Platform
"""

import json
import os
import random
import time
from datetime import datetime, timezone

# Ensure output logs directory exists
LOGS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "logs")
os.makedirs(LOGS_DIR, exist_ok=True)
LOG_FILE_PATH = os.path.join(LOGS_DIR, "cloud_events.json")


class CloudTelemetrySimulator:
    """Simulates raw cloud audit logs and network telemetry from AWS CloudTrail and Honeypots."""

    def __init__(self):
        self.sample_ips = [
            "192.168.1.105",   # Internal harmless user
            "185.220.101.5",   # Tor Exit Node / Known malicious IP
            "45.33.32.156",    # External Scanner IP
            "10.0.0.42",       # Internal DB Server
            "198.51.100.22"    # Suspicious Remote Access IP
        ]

        self.event_templates = [
            {
                "event_source": "aws.ec2",
                "event_name": "AuthorizeSecurityGroupIngress",
                "user_identity": "arn:aws:iam::123456789012:user/admin",
                "details": "Opened Port 22 (SSH) to 0.0.0.0/0 (Global Access)",
                "base_severity": "HIGH"
            },
            {
                "event_source": "aws.s3",
                "event_name": "PutBucketPolicy",
                "user_identity": "arn:aws:iam::123456789012:user/developer",
                "details": "Modified S3 Bucket Policy to allow Public Read access",
                "base_severity": "CRITICAL"
            },
            {
                "event_source": "honeypot.ssh",
                "event_name": "FailedPasswordAttempt",
                "user_identity": "root",
                "details": "Brute force attack detected on SSH honeypot (Port 2222)",
                "base_severity": "HIGH"
            },
            {
                "event_source": "aws.iam",
                "event_name": "AttachUserPolicy",
                "user_identity": "arn:aws:iam::123456789012:user/contractor",
                "details": "Attached AdministratorAccess policy to low-privilege user",
                "base_severity": "CRITICAL"
            },
            {
                "event_source": "aws.ec2",
                "event_name": "DescribeInstances",
                "user_identity": "arn:aws:iam::123456789012:user/analyst",
                "details": "Normal read-only query on EC2 instances list",
                "base_severity": "LOW"
            }
        ]

    def generate_event(self) -> dict:
        """Generates a single synthetic Cloud Security event formatted as JSON telemetry."""
        template = random.choice(self.event_templates)
        source_ip = random.choice(self.sample_ips)
        
        event = {
            "event_id": f"evt-{int(time.time() * 1000)}-{random.randint(100, 999)}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source_ip": source_ip,
            "event_source": template["event_source"],
            "event_name": template["event_name"],
            "user_identity": template["user_identity"],
            "details": template["details"],
            "base_severity": template["base_severity"]
        }
        return event

    def generate_batch(self, count: int = 10) -> list:
        """Generates a batch of synthetic security events and writes them to disk."""
        events = [self.generate_event() for _ in range(count)]
        
        with open(LOG_FILE_PATH, "w", encoding="utf-8") as f:
            json.dump(events, f, indent=4)
            
        print(f"[+] Successfully generated {count} synthetic telemetry events -> {LOG_FILE_PATH}")
        return events


class CloudLogParser:
    """Parses and categorizes telemetry logs generated by cloud security services."""

    def __init__(self, file_path: str = LOG_FILE_PATH):
        self.file_path = file_path

    def parse_and_summarize(self):
        """Reads raw event telemetry and outputs a structured security summary."""
        if not os.path.exists(self.file_path):
            print(f"[-] Error: Log file {self.file_path} does not exist. Run simulator first.")
            return None

        with open(self.file_path, "r", encoding="utf-8") as f:
            events = json.load(f)

        severity_counts = {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "CRITICAL": 0}
        suspicious_ips = set()

        for event in events:
            sev = event.get("base_severity", "LOW")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1
            
            if sev in ["HIGH", "CRITICAL"]:
                suspicious_ips.add(event.get("source_ip"))

        summary = {
            "total_events_processed": len(events),
            "severity_breakdown": severity_counts,
            "high_risk_source_ips": list(suspicious_ips)
        }

        return summary


def run_module_1_demo():
    print("==================================================")
    print("      MODULE 1: CLOUD TELEMETRY DEMO & PARSER     ")
    print("==================================================")
    
    # Step 1: Initialize Simulator & Generate Logs
    simulator = CloudTelemetrySimulator()
    generated_events = simulator.generate_batch(count=15)
    
    # Display sample generated event
    print("\n[Sample Log Event Captured]:")
    print(json.dumps(generated_events[0], indent=2))
    
    # Step 2: Initialize Parser & Summarize
    parser = CloudLogParser()
    summary = parser.parse_and_summarize()
    
    print("\n[Parsed Security Telemetry Summary]:")
    print(json.dumps(summary, indent=2))
    print("\n[✓] Module 1 Simulation Execution Complete.")


if __name__ == "__main__":
    run_module_1_demo()
